on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Apt packages
        run: sudo apt install -y --no-install-recommends g++ libgomp1 make python3 zlib1g-dev wget

      - name: Cache Bgen
        id: cache-bgen
        uses: actions/cache@v2
        with:
          path: v1.1.7.tgz
          key: ${{ runner.os }}-bgentgz

      - name: Wget Bgen
        if: steps.cache-bgentgz.outputs.cache-hit != 'true'
        run: |
          wget "http://code.enkre.net/bgen/tarball/release/v1.1.7.tgz"

      - name: Install Bgen
        run: |
          tar xzf v1.1.7.tgz
          pushd v1.1.7
          python3 waf configure
          python3 waf
          popd
        env:
          BOOST_IO: 1

      - name: Build
        run: make BGEN_PATH=./v1.1.7 HAS_BOOST_IOSTREAM=$BOOST_IO STATIC=$STATIC all
        env:
          BOOST_IO: 1
          STATIC: 1

      - name: Test
        run: ./regenie --help
