on: [push, pull_request]

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Apt packages
        run: sudo apt install -y --no-install-recommends g++ libgomp1 make python3 zlib1g-dev wget

      - name: Get Bgen
        run: wget "http://code.enkre.net/bgen/tarball/release/v1.1.7.tgz" && tar xzf v1.1.7.tgz && rm v1.1.7.tgz

      - name: Build Bgen
        run: pushd v1.1.7 && python3 waf configure && python3 waf && popd

      - name: Build Regenie
        run: (pwd && ls Makefile || cd .. && ls -la) && make BGEN_PATH=./v1.1.7 HAS_BOOST_IOSTREAM=1 STATIC=1 all
