on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Apt packages
        run: sudo apt install -y --no-install-recommends g++ libgomp1 make python3 zlib1g-dev wget

      - name: Cache Primes
        id: cache-bgen
        uses: actions/cache@v2
        with:
          path: v1.1.7
          key: ${{ runner.os }}-bgen

      - name: Get Bgen
        if: steps.cache-bgen.outputs.cache-hit != 'true'
        run: |
          wget "http://code.enkre.net/bgen/tarball/release/v1.1.7.tgz"
          tar xzf v1.1.7.tgz
          rm v1.1.7.tgz
          pushd v1.1.7
          python3 waf configure
          python3 waf
          popd

      - name: Build
        run: (pwd && ls Makefile || cd .. && ls -la) && make BGEN_PATH=./v1.1.7 HAS_BOOST_IOSTREAM=0 STATIC=1 all

      - name: Test
        run: ./regenie --help
